apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: umami
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: info@connecty.nl
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - http01:
          ingress:
            class: nginx