apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - postgres/deployment.yml
  - postgres/pv-volume.yml
  - postgres/pv-claim.yml
  - postgres/service.yml
  - frontend/deployment.yml
  - frontend/ingress.yml
  - frontend/cert_issuer.yml
  - frontend/service.yml