apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: umami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: postgresdb
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: umami
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: stats-postgres-pv-volume
      volumes:
        - name: stats-postgres-pv-volume
          persistentVolumeClaim:
            claimName: stats-postgres-pv-claim